//define an object made of 3 arrays: adj(adjective), obj (object), and med (medium). Each with 50 words. 
const words = {
    adj: [ "happy",
    "sad",
    "angry",
    "calm",
    "tired",
    "energetic",
    "funny",
    "serious",
    "silly",
    "intelligent",
    "stupid",
    "creative",
    "boring",
    "exciting",
    "scary",
    "safe",
    "dangerous",
    "clean",
    "dirty",
    "fresh",
    "stale",
    "soft",
    "hard",
    "smooth",
    "rough",
    "light",
    "heavy",
    "big",
    "small",
    "short",
    "tall",
    "young",
    "old",
    "fast",
    "slow",
    "hot",
    "cold",
    "wet",
    "dry",
    "sweet",
    "sour",
    "spicy",
    "loud",
    "quiet",
    "bright",
    "dark",
    "shiny",
    "dull",
    "happy",
    "sleepy"],
    obj: [ "chair",
    "table",
    "lamp",
    "couch",
    "bookshelf",
    "vase",
    "picture frame",
    "teapot",
    "mirror",
    "clock",
    "rug",
    "book",
    "plant",
    "basket",
    "candle",
    "blanket",
    "pillow",
    "curtains",
    "sculpture",
    "statue",
    "globe",
    "kitchen utensils",
    "cutlery",
    "coffee mug",
    "teacup",
    "wine glass",
    "water bottle",
    "tissue box",
    "toilet brush",
    "soap dispenser",
    "towel rack",
    "shower curtain",
    "toothbrush holder",
    "hairbrush",
    "makeup mirror",
    "jewelry box",
    "camera",
    "cell phone",
    "laptop",
    "keyboard",
    "mouse",
    "printer",
    "scanner",
    "external hard drive",
    "flash drive",
    "headphones",
    "speaker",
    "microphone",
    "remote control",
    "pen"],
    med: ["acrylic paint",
    "oil paint",
    "watercolor",
    "colored pencils",
    "graphite pencils",
    "charcoal",
    "ink",
    "pastels",
    "clay",
    "digital art",
    "photography",
    "mixed media",
    "collage",
    "encaustic",
    "gouache",
    "tempera",
    "printmaking",
    "airbrushing",
    "spray paint",
    "textiles",
    "embroidery",
    "quilting",
    "weaving",
    "knitting",
    "crocheting",
    "lace-making",
    "leatherworking",
    "glassblowing",
    "ceramics",
    "jewelry making",
    "metalworking",
    "woodworking",
    "calligraphy",
    "letterpress",
    "bookbinding",
    "origami",
    "paper-cutting",
    "carving",
    "sculpture",
    "performance art",
    "video art",
    "installation art",
    "street art",
    "graffiti",
    "animation",
    "comic art",
    "children's book illustration",
    "scientific illustration",
    "fashion illustration",
    "found obejct art"]
}

// console.log(words)

const randNum = () => {
    return Math.floor(Math.random() * 50)
}

//ENSURES THE RANDNUM WORKS
// for (let i = 0; i < 10; i++){
//     console.log(randNum())
// }


//ENSURES THERE ARE 50 WORDS IN EACH ARRAY
// console.log(`ajective array length: ${words.adj.length} ....... object array length: ${words.obj.length}.......... medium array length: ${words.med.length}`)


//PRINT ART PROMPT
console.log(`Art Prompt: ${words.adj[randNum()]} ${words.obj[randNum()]} in ${words.med[randNum()]}`)